language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mmore500
  password:
    secure: A9Vfiq/2v+cTm+HyLTLXCmYdEdLJISSGwBCXcg2S5WGjJtMXd+mpRL3piXw4Sph/Oox+jM71UPRylP292AV4JAlKChjIAtqATIqhlgJLRYRRKBHtQwwHNX3q+rAmucYy3nQ4ypUuZhEW0TH2AkCfYNoU1yvMxqyc+g6os3Rb+vrumr+y9noFh1Gx53w9b1Q1LHwcgiZixs9a569Fio798fzTNjT+aISHOY+SzQxK39rxZNxdyYTplltL3lZNo45PAOa0dsY1g2cMnM82sUDLwnWn4ZXG73Sw6oCe/uSI6KfbyvAPhpIV2lwpyngpn7B3kLQZYhCrEDflIYEXuYQa49Hms98O9TPTbUsLOrDh/ePizuK23iTAmEh/yfs9KPKXRsHzOOwC/tbVkZmTi+ZXZXv0syCgAn1bht5qf5qwbzCuE4rKC30xbxY1Ct/it5NCjwWW2z65fGc6Q6BG73K4tyvRhUPaqbqfl23969n0g/Ja1Jlaz/KWJeDEulXinng8BL/MIHCoffzrExZDK2LtT53IvDTG2lM0c4rcl7rxacFZOGmsa034JQwx4LKsCxEDb+E15lpFUiR+t/7slxBsRKXAcIic/nnhUEuKzbxYFXooEljwKSSslrjvg87+uMkYMrJNART3ESXNIq8Av7IEwaJmFl9nNuQF3RTiM7oV4Qk=
  on:
    tags: true
    repo: mmore500/keyname
    python: 3.6
